# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_title', models.CharField(max_length=32)),
                ('carousel_content', models.CharField(max_length=32)),
            ],
        ),
    ]
