# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_content',
            field=models.TextField(max_length=255),
        ),
    ]
